version: "3.9"

services:
  api:
    container_name: api_cdl_onr
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://admin:1234@db:5432/db_cdl_onr
      - SECRET_KEY=123456
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db_cdl_onr
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_cdl_onr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db_cdl_onr"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


